A.1 ndarray Object Internals

In [1]:
import numpy as np

np.ones((10, 5)).shape

(10, 5)

In [2]:
np.ones((3, 4, 5), dtype=np.float64).strides

(160, 40, 8)

In [4]:
# NumPy dtype Hierarchy

ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)
np.issubdtype(ints.dtype, np.integer)



True

In [5]:
np.issubdtype(floats.dtype, np.floating)

True

In [6]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [7]:
np.issubdtype(ints.dtype, np.number)

True

A.2 Advanced Array Manipulation

In [ ]:
# Reshaping Arrays

arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [9]:
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [10]:
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [11]:
arr = np.arange(15)
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [13]:
other_arr = np.ones((3, 5))
other_arr.shape

(3, 5)

In [14]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [16]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
# C Versus Fortan Order

arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [22]:
# Concatenating and Splitting Arrays

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [24]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [26]:
arr = np.random.randn(5, 2)
arr

array([[-0.17436422,  0.38463187],
       [ 0.77542162, -0.79090572],
       [ 0.40936218, -0.47497652],
       [-1.72991043,  0.0289211 ],
       [ 0.25482025,  1.05906761]])

In [27]:
first, second, third = np.split(arr, [1, 3])
first

array([[-0.17436422,  0.38463187]])

In [28]:
second

array([[ 0.77542162, -0.79090572],
       [ 0.40936218, -0.47497652]])

In [29]:
third

array([[-1.72991043,  0.0289211 ],
       [ 0.25482025,  1.05906761]])

In [30]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = np.random.randn(3, 2)
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [-1.5938487 , -0.27839344],
       [ 0.23748079, -0.26041985],
       [-0.88342441, -1.65434689]])

In [31]:
np.c_[np.r_[arr1, arr2], arr]

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [-1.5938487 , -0.27839344,  3.        ],
       [ 0.23748079, -0.26041985,  4.        ],
       [-0.88342441, -1.65434689,  5.        ]])

In [32]:
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

In [33]:
# Repeating Elements: tile and repeat

arr = np.arange(3)
arr

array([0, 1, 2])

In [34]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [35]:
arr.repeat([2, 3, 4])


array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [37]:
arr = np.random.randn(2, 2)
arr

array([[ 0.81930283, -1.50233923],
       [ 0.13100958,  1.38094736]])

In [38]:
arr.repeat(2, axis=0)

array([[ 0.81930283, -1.50233923],
       [ 0.81930283, -1.50233923],
       [ 0.13100958,  1.38094736],
       [ 0.13100958,  1.38094736]])

In [39]:
arr.repeat([2, 3], axis=0)

array([[ 0.81930283, -1.50233923],
       [ 0.81930283, -1.50233923],
       [ 0.13100958,  1.38094736],
       [ 0.13100958,  1.38094736],
       [ 0.13100958,  1.38094736]])

In [40]:
arr.repeat([2, 3], axis=1)

array([[ 0.81930283,  0.81930283, -1.50233923, -1.50233923, -1.50233923],
       [ 0.13100958,  0.13100958,  1.38094736,  1.38094736,  1.38094736]])

In [41]:
arr

array([[ 0.81930283, -1.50233923],
       [ 0.13100958,  1.38094736]])

In [42]:
np.tile(arr, (2, 1))

array([[ 0.81930283, -1.50233923],
       [ 0.13100958,  1.38094736],
       [ 0.81930283, -1.50233923],
       [ 0.13100958,  1.38094736]])

In [43]:
np.tile(arr, (3, 2))

array([[ 0.81930283, -1.50233923,  0.81930283, -1.50233923],
       [ 0.13100958,  1.38094736,  0.13100958,  1.38094736],
       [ 0.81930283, -1.50233923,  0.81930283, -1.50233923],
       [ 0.13100958,  1.38094736,  0.13100958,  1.38094736],
       [ 0.81930283, -1.50233923,  0.81930283, -1.50233923],
       [ 0.13100958,  1.38094736,  0.13100958,  1.38094736]])

In [44]:
# Facy Indexing Equivalents: take and put

arr = np.arange(10) * 100
inds = [7, 1, 2, 6]
arr[inds]

array([700, 100, 200, 600])

In [45]:
arr.take(inds)

array([700, 100, 200, 600])

In [47]:
arr.put(inds, 42)
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [48]:
inds = [2, 0, 2, 1]
arr = np.random.randn(2, 4)
arr

array([[-0.6050039 , -0.63999527, -0.25797005, -0.98507493],
       [ 0.62629298,  0.39179615, -1.42568854,  0.07293799]])

In [49]:
arr.take(inds, axis=1)

array([[-0.25797005, -0.6050039 , -0.25797005, -0.63999527],
       [-1.42568854,  0.62629298, -1.42568854,  0.39179615]])