4.1. NumP ndarray - multidimensional array object

In [25]:
# Creating ndarrays

import numpy as np

data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

arr2.ndim
arr2.shape

arr1.dtype
arr2.dtype

np.zeros(10)
np.zeros((3, 6))
np.empty((2, 3, 2))

np.arange(15)



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
# Ndarray array data type

arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1 = np.array([1, 2, 3], dtype=np.int32)

arr1.dtype
arr2.dtype

arr = np.array([1, 2, 3, 4, 5])
arr.dtype

float_arr = arr.astype(np.float64)
float_arr.dtype

arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)

numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.bytes_)
numeric_strings.astype(float)

int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

int_array.astype(calibers.dtype)

empty_uint32 = np.empty(8, dtype=np.uint32)
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [45]:
# Mathematical operations with NumPy arrays

arr = np.array([[1., 2., 3.], [4., 5., 6.]])

arr
arr * arr
arr - arr
1 / arr
arr ** 0.5

arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [67]:
# Basics of indexing and part capturing

arr = np.arange(10)
arr

arr[5]
arr[5:8]

arr[5:8] = 12
arr

arr_slice = arr[5:8]
arr_slice

arr_slice[1] = 12345
arr

arr_slice[:] = 64
arr

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

arr2d[0][2]
arr2d[0, 2]

arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

arr3d[0]

old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

arr3d[0] = old_values
arr3d

arr3d[1, 0]

x = arr3d[1]
x
x[0]


array([7, 8, 9])

In [77]:
# Indexing by Slicing Arrays

arr
arr[1:6]

arr2d
arr2d[:2]
arr2d[:2, 1:]
arr2d[1, :2]
arr2d[:2, 2]
arr2d[:, :1]

arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [94]:
# Indexing and Boolean Values

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

names
data

names == 'Bob'
data[names == 'Bob']
data[names == 'Bob', 2:]
data[names == 'Bob', 3]
names != 'Bob'
data[~(names == 'Bob')]

cond = names == 'Bob'
data[~cond]

mask = (names == 'Bob') | (names == 'Will')
mask

data[mask]

data[data < 0] = 0
data

data[names != 'Joe'] = 7
data



array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.04186263, 1.09840791, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.55733711, 0.09326053, 0.30549156],
       [0.        , 0.28106588, 0.        , 1.27255999]])

In [101]:
# Fancy indexing

arr = np.empty((8, 4))

for i in range(8):
    arr[i] = i

arr

arr[[4, 3, 0, 6]]
arr[[-3, -5, -7]]

arr = np.arange(32).reshape((8, 4))
arr

arr[[1, 5, 7, 2], [0, 3, 1, 2]]

arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [109]:
# Transposing tables and changing axes

arr = np.arange(15).reshape((3, 5))

arr
arr.T

arr = np.random.randn(6, 3)
arr
np.dot(arr.T, arr)

arr = np.arange(16).reshape((2, 2, 4))
arr
arr.transpose((1, 0, 2))

arr
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])